### ISSUE TITLE
Using the contrib version of otel collector

### ISSUE THREAD

**Issue by jtfell** [lightstep/opentelemetry-lambda-extension#1]
Is it possible to use the [contrib version](https://github.com/open-telemetry/opentelemetry-collector-contrib) of the collector module? I would like to try this out with Datadog but their exporter is only in the contrib repo

**Comment by codeboten** [comment]
hey @jtfell! the contents for this repo now live in https://github.com/open-telemetry/opentelemetry-lambda, there's a discussion regarding exporters for the collector here: https://github.com/open-telemetry/opentelemetry-lambda/issues/22
